Repository Gagechaeum/backend, pull requests merged in 2025-09, with the labels that each got.

#5 [Feature] #4 : 정책 추천 조회 API
  database.sql
  src/main/java/com/gagechaeum/backend/common/response/CustomResponse.java
  src/main/java/com/gagechaeum/backend/common/response/ResponseCode.java
  src/main/java/com/gagechaeum/backend/global/config/AppConfig.java
  src/main/java/com/gagechaeum/backend/policy/controller/PolicyController.java
  src/main/java/com/gagechaeum/backend/policy/domain/Policy.java
  src/main/java/com/gagechaeum/backend/policy/dto/response/PolicyInfoDTO.java
  src/main/java/com/gagechaeum/backend/policy/dto/response/PolicyRecommendationResponseDTO.java
  src/main/java/com/gagechaeum/backend/policy/mapper/PolicyMapper.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicyService.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicyServiceImpl.java
  src/main/java/com/gagechaeum/backend/user/domain/User.java
  src/main/resources/application.properties
  src/main/resources/com/gagechaeum/backend/policy/mapper/PolicyMapper.xml
Labels: ✨New Feature

#13 [Feature] #6 : 대출 추천 조회 API 구현 및 정책 데이터 동기화 기능 추가
  database.sql
  init.sql
  src/main/java/com/gagechaeum/backend/common/util/DateParserUtil.java
  src/main/java/com/gagechaeum/backend/global/config/AppConfig.java
  src/main/java/com/gagechaeum/backend/loan/controller/LoanController.java
  src/main/java/com/gagechaeum/backend/loan/domain/Loan.java
  src/main/java/com/gagechaeum/backend/loan/dto/response/LoanInfoDTO.java
  src/main/java/com/gagechaeum/backend/loan/dto/response/LoanRecommendationResponseDTO.java
  src/main/java/com/gagechaeum/backend/loan/mapper/LoanMapper.java
  src/main/java/com/gagechaeum/backend/loan/service/LoanService.java
  src/main/java/com/gagechaeum/backend/loan/service/LoanServiceImpl.java
  src/main/java/com/gagechaeum/backend/policy/client/Gov24ApiClient.java
  src/main/java/com/gagechaeum/backend/policy/controller/PolicyController.java
  src/main/java/com/gagechaeum/backend/policy/domain/Policy.java
  src/main/java/com/gagechaeum/backend/policy/dto/external/Gov24ApiResponseDto.java
  src/main/java/com/gagechaeum/backend/policy/dto/external/Gov24ApiServiceDto.java
  src/main/java/com/gagechaeum/backend/policy/dto/response/PolicyInfoDTO.java
  src/main/java/com/gagechaeum/backend/policy/mapper/PolicyMapper.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicyServiceImpl.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicySyncService.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicySyncServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/com/gagechaeum/backend/loan/mapper/LoanMapper.xml
  src/main/resources/com/gagechaeum/backend/policy/mapper/PolicyMapper.xml
Labels: ✨New Feature

#17 [Feature] #15 : 리포트 종합 데이터 조회 API 구현
  src/main/java/com/gagechaeum/backend/report/controller/ReportController.java
  src/main/java/com/gagechaeum/backend/report/domain/Repayment.java
  src/main/java/com/gagechaeum/backend/report/domain/UserLoan.java
  src/main/java/com/gagechaeum/backend/report/domain/UserPolicy.java
  src/main/java/com/gagechaeum/backend/report/dto/response/DashboardResponse.java
  src/main/java/com/gagechaeum/backend/report/mapper/ReportMapper.java
  src/main/java/com/gagechaeum/backend/report/service/ReportService.java
  src/main/java/com/gagechaeum/backend/report/service/ReportServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/com/gagechaeum/backend/report/mapper/ReportMapper.xml
Labels: ✨New Feature

#23 [Feature] #21 : 관심 정책 검색 API 구현
  src/main/java/com/gagechaeum/backend/report/controller/ReportController.java
  src/main/java/com/gagechaeum/backend/report/domain/PolicySearchResult.java
  src/main/java/com/gagechaeum/backend/report/dto/response/PolicySearchResponseDTO.java
  src/main/java/com/gagechaeum/backend/report/mapper/ReportMapper.java
  src/main/java/com/gagechaeum/backend/report/service/ReportService.java
  src/main/java/com/gagechaeum/backend/report/service/ReportServiceImpl.java
  src/main/resources/com/gagechaeum/backend/report/mapper/ReportMapper.xml
Labels: ✨New Feature

#26 [Feature] #25 : 사용자 서류 삭제 API 구현
  src/main/java/com/gagechaeum/backend/common/util/S3ClientUtil.java
  src/main/java/com/gagechaeum/backend/document/controller/UserDocumentController.java
  src/main/java/com/gagechaeum/backend/document/dto/UserDocumentDeleteRequestDto.java
  src/main/java/com/gagechaeum/backend/document/dto/UserDocumentUploadRequestDto.java
  src/main/java/com/gagechaeum/backend/document/mapper/UserDocumentMapper.java
  src/main/java/com/gagechaeum/backend/document/service/UserDocumentService.java
  src/main/java/com/gagechaeum/backend/document/service/UserDocumentServiceImpl.java
  src/main/resources/com/gagechaeum/backend/document/mapper/UserDocumentMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
Labels: ✨New Feature

#28 [Feature] #27 : 사용자 서류 다운로드 API 구현
  init.sql
  src/main/java/com/gagechaeum/backend/common/util/S3ClientUtil.java
  src/main/java/com/gagechaeum/backend/document/controller/UserDocumentController.java
  src/main/java/com/gagechaeum/backend/document/domain/UserDocument.java
  src/main/java/com/gagechaeum/backend/document/dto/UserDocumentDeleteRequestDto.java
  src/main/java/com/gagechaeum/backend/document/dto/UserDocumentDownloadResponseDto.java
  src/main/java/com/gagechaeum/backend/document/mapper/UserDocumentMapper.java
  src/main/java/com/gagechaeum/backend/document/service/UserDocumentService.java
  src/main/java/com/gagechaeum/backend/document/service/UserDocumentServiceImpl.java
  src/main/resources/com/gagechaeum/backend/document/mapper/UserDocumentMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
Labels: ✨New Feature

#45 [Feature] #42 : 채팅방 목록 조회 API 구현
  init.sql
  src/main/java/com/gagechaeum/backend/chat/controller/ChatController.java
  src/main/java/com/gagechaeum/backend/chat/controller/chatController.txt
  src/main/java/com/gagechaeum/backend/chat/dto/ChatRoomListResponseDto.java
  src/main/java/com/gagechaeum/backend/chat/dto/ChatRoomSummaryDto.java
  src/main/java/com/gagechaeum/backend/chat/mapper/ChatMapper.java
  src/main/java/com/gagechaeum/backend/chat/mapper/chatMapper.txt
  src/main/java/com/gagechaeum/backend/chat/service/ChatService.java
  src/main/java/com/gagechaeum/backend/chat/service/ChatServiceImpl.java
  src/main/java/com/gagechaeum/backend/chat/service/chatService.txt
  src/main/java/com/gagechaeum/backend/loan/mapper/LoanMapper.java
  src/main/java/com/gagechaeum/backend/policy/mapper/PolicyMapper.java
  src/main/resources/com/gagechaeum/backend/chat/mapper/ChatMapper.xml
  src/main/resources/com/gagechaeum/backend/chat/mapper/chatMapper.txt
  src/main/resources/mybatis/mybatis-config.xml
Labels: ✨New Feature

#48 [Feature] #44 : 서류 현황 조회 API
  init.sql
  src/main/java/com/gagechaeum/backend/application/controller/ApplicationController.java
  src/main/java/com/gagechaeum/backend/application/dto/request/ApplicationStatusUpdateRequestDTO.java
  src/main/java/com/gagechaeum/backend/application/dto/response/ApplicationResponseDTO.java
  src/main/java/com/gagechaeum/backend/application/mapper/ApplicationMapper.java
  src/main/java/com/gagechaeum/backend/application/service/ApplicationService.java
  src/main/java/com/gagechaeum/backend/application/service/ApplicationServiceImpl.java
  src/main/resources/com/gagechaeum/backend/application/mapper/ApplicationMapper.xml
Labels: ✨New Feature

#56 [Fix] : 채팅방 목록 조회 코드 누락
  src/main/java/com/gagechaeum/backend/chat/service/ChatServiceImpl.java
Labels: ✨New Feature

#58 [Fix] #55 : 서류 관리 기능 테스트 및 수정
  build.gradle
  src/main/java/com/gagechaeum/backend/common/util/Constants.java
  src/main/java/com/gagechaeum/backend/common/util/S3ClientUtil.java
  src/main/java/com/gagechaeum/backend/document/controller/UserDocumentController.java
  src/main/java/com/gagechaeum/backend/document/dto/UserDocumentDownloadResponseDto.java
  src/main/java/com/gagechaeum/backend/document/dto/UserDocumentUploadRequestDto.java
  src/main/java/com/gagechaeum/backend/document/mapper/UserDocumentMapper.java
  src/main/java/com/gagechaeum/backend/document/service/UserDocumentService.java
  src/main/java/com/gagechaeum/backend/document/service/UserDocumentServiceImpl.java
  src/main/java/com/gagechaeum/backend/global/config/ServletConfig.java
  src/main/java/com/gagechaeum/backend/global/config/WebConfig.java
  src/main/resources/com/gagechaeum/backend/document/mapper/UserDocumentMapper.xml
  user.sql
Labels: ✨New Feature

#61 [Fix] #49 : 서류 현황 조회 API 즐겨찾기 대상으로 수정
  init.sql
  src/main/resources/com/gagechaeum/backend/application/mapper/ApplicationMapper.xml
  src/main/resources/com/gagechaeum/backend/user/mapper/UserMapper.xml
Labels: 🐞Bug Fix

#68 [Fix]: 알림설정기능 수정 및 유저기본정보 변경 추가
  src/main/java/com/gagechaeum/backend/common/response/ResponseCode.java
  src/main/java/com/gagechaeum/backend/security/account/domain/CustomUserDetails.java
  src/main/java/com/gagechaeum/backend/user/controller/UserController.java
  src/main/java/com/gagechaeum/backend/user/dto/UpdateUserDTO.java
  src/main/java/com/gagechaeum/backend/user/dto/UserInfoResponseDTO.java
  src/main/java/com/gagechaeum/backend/user/dto/UserJoinRequestDTO.java
  src/main/java/com/gagechaeum/backend/user/mapper/UserMapper.java
  src/main/java/com/gagechaeum/backend/user/service/UserService.java
  src/main/java/com/gagechaeum/backend/user/service/UserServiceImpl.java
  src/main/resources/com/gagechaeum/backend/user/mapper/UserMapper.xml
Labels: 🐞Bug Fix

#72 [Feature] #72 : 사용자 채팅방 목록 조회 API
  loans.sql
  src/main/java/com/gagechaeum/backend/chat/controller/ChatController.java
  src/main/java/com/gagechaeum/backend/chat/controller/UserChatController.java
  src/main/java/com/gagechaeum/backend/chat/dto/UserChatRoomListResponseDto.java
  src/main/java/com/gagechaeum/backend/chat/dto/UserChatRoomSummaryDto.java
  src/main/java/com/gagechaeum/backend/chat/mapper/ChatMapper.java
  src/main/java/com/gagechaeum/backend/chat/service/ChatService.java
  src/main/java/com/gagechaeum/backend/chat/service/ChatServiceImpl.java
  src/main/java/com/gagechaeum/backend/policy/dto/response/PolicyListResponseDto.java
  src/main/java/com/gagechaeum/backend/policy/dto/response/PolicySummaryDto.java
  src/main/resources/com/gagechaeum/backend/chat/mapper/ChatMapper.xml
  user.sql
Labels: ✨New Feature

#75 [Feature] #62 : 즐겨찾기 상품에 필요한 서류 조회 API
  build.gradle
  init.sql
  src/main/java/com/gagechaeum/backend/application/controller/ApplicationController.java
  src/main/java/com/gagechaeum/backend/application/mapper/ApplicationMapper.java
  src/main/java/com/gagechaeum/backend/application/service/ApplicationService.java
  src/main/java/com/gagechaeum/backend/application/service/ApplicationServiceImpl.java
  src/main/java/com/gagechaeum/backend/bookmark/controller/BookmarkController.java
  src/main/java/com/gagechaeum/backend/bookmark/dto/request/BookmarkStatusUpdateRequestDTO.java
  src/main/java/com/gagechaeum/backend/bookmark/dto/response/BookmarkDocumentsResponseDTO.java
  src/main/java/com/gagechaeum/backend/bookmark/dto/response/BookmarkResponseDTO.java
  src/main/java/com/gagechaeum/backend/bookmark/mapper/BookmarkMapper.java
  src/main/java/com/gagechaeum/backend/bookmark/service/BookmarkService.java
  src/main/java/com/gagechaeum/backend/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/gagechaeum/backend/global/config/AppConfig.java
  src/main/java/com/gagechaeum/backend/global/config/ServletConfig.java
  src/main/java/com/gagechaeum/backend/policy/client/Gov24ApiClient.java
  src/main/java/com/gagechaeum/backend/policy/controller/PolicyController.java
  src/main/java/com/gagechaeum/backend/policy/domain/Policy.java
  src/main/java/com/gagechaeum/backend/policy/dto/DocumentKeywordDTO.java
  src/main/java/com/gagechaeum/backend/policy/dto/external/Gov24ApiDetailResponseDto.java
  src/main/java/com/gagechaeum/backend/policy/dto/response/PolicyDetailResponseDto.java
  src/main/java/com/gagechaeum/backend/policy/dto/response/PolicyDocumentsResponseDTO.java
  src/main/java/com/gagechaeum/backend/policy/mapper/PolicyMapper.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicyService.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicyServiceImpl.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicySyncService.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicySyncServiceImpl.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicyUpdateService.java
  src/main/java/com/gagechaeum/backend/report/controller/ReportController.java
  src/main/java/com/gagechaeum/backend/report/dto/response/DashboardResponseDTO.java
  src/main/java/com/gagechaeum/backend/report/service/ReportService.java
  src/main/java/com/gagechaeum/backend/report/service/ReportServiceImpl.java
  src/main/resources/com/gagechaeum/backend/application/mapper/ApplicationMapper.xml
  src/main/resources/com/gagechaeum/backend/bookmark/mapper/BookmarkMapper.xml
  src/main/resources/com/gagechaeum/backend/policy/mapper/PolicyMapper.xml
  src/main/resources/log4j.xml
Labels: ✨New Feature, 🐞Bug Fix

#81 [Feature] #74 : 채팅방 입장 기능 구현
  build.gradle
  src/main/java/com/gagechaeum/backend/chat/config/WebSocketConfig.java
  src/main/java/com/gagechaeum/backend/chat/controller/ChatStompController.java
  src/main/java/com/gagechaeum/backend/chat/dto/ChatHistoryMessageDto.java
  src/main/java/com/gagechaeum/backend/chat/dto/ChatMessageDto.java
  src/main/java/com/gagechaeum/backend/chat/dto/ChatRoomHistoryResponseDto.java
  src/main/java/com/gagechaeum/backend/chat/interceptor/JwtChannelInterceptor.java
  src/main/java/com/gagechaeum/backend/chat/interceptor/JwtHandshakeInterceptor.java
  src/main/java/com/gagechaeum/backend/chat/mapper/ChatMapper.java
  src/main/java/com/gagechaeum/backend/common/redis/RedisConfig.java
  src/main/java/com/gagechaeum/backend/common/redis/RedisMessageSubscriber.java
  src/main/resources/com/gagechaeum/backend/chat/mapper/ChatMapper.xml
Labels: ✨New Feature

#90 [Fix] : sql 파일 수정 및 병합
  chat.sql
  dummy.sql
  init.sql
  src/main/resources/com/gagechaeum/backend/policy/mapper/PolicyMapper.xml
  user.sql
Labels: 🐞Bug Fix

#91 [Fix] : 회원가입 및 마이페이지 1차수정
  src/main/java/com/gagechaeum/backend/common/redis/RedisKeyPrefix.java
  src/main/java/com/gagechaeum/backend/security/account/domain/CustomUserDetails.java
  src/main/java/com/gagechaeum/backend/security/util/JwtUtil.java
  src/main/java/com/gagechaeum/backend/user/controller/BusinessInfoController.java
  src/main/java/com/gagechaeum/backend/user/controller/UserController.java
  src/main/java/com/gagechaeum/backend/user/dto/UserInfoResponseDTO.java
  src/main/java/com/gagechaeum/backend/user/service/BusinessInfoService.java
  src/main/java/com/gagechaeum/backend/user/service/BusinessInfoServiceImpl.java
  src/main/java/com/gagechaeum/backend/user/service/UserService.java
  src/main/java/com/gagechaeum/backend/user/service/UserServiceImpl.java
  src/main/resources/com/gagechaeum/backend/user/mapper/BusinessInfoMapper.xml
Labels: 🐞Bug Fix

#93 [Feature] #92 : 상품별 서류 체크리스트 조회 api 구현
  init.sql
  src/main/java/com/gagechaeum/backend/document/controller/DocumentChecklistController.java
  src/main/java/com/gagechaeum/backend/document/dto/ProductInfo.java
  src/main/java/com/gagechaeum/backend/document/dto/response/DocumentChecklistResponseDto.java
  src/main/java/com/gagechaeum/backend/document/mapper/DocumentMapper.java
  src/main/java/com/gagechaeum/backend/document/service/DocumentChecklistService.java
  src/main/java/com/gagechaeum/backend/document/service/DocumentChecklistServiceImpl.java
  src/main/resources/com/gagechaeum/backend/document/mapper/DocumentMapper.xml
  src/main/resources/com/gagechaeum/backend/document/mapper/RequiredDocumentMapper.xml
Labels: ✨New Feature

#95 [Feature] 키워드로 정책-지역/업종 코드 매핑
  build.gradle
  dummy.sql
  init.sql
  src/main/java/com/gagechaeum/backend/policy/domain/Industry.java
  src/main/java/com/gagechaeum/backend/policy/domain/Regions.java
  src/main/java/com/gagechaeum/backend/policy/mapper/IndustryMapper.java
  src/main/java/com/gagechaeum/backend/policy/mapper/PolicyMapper.java
  src/main/java/com/gagechaeum/backend/policy/mapper/RegionMapper.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicyMatchingService.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicyMatchingServiceImpl.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicySyncServiceImpl.java
  src/main/resources/com/gagechaeum/backend/policy/mapper/IndustryMapper.xml
  src/main/resources/com/gagechaeum/backend/policy/mapper/PolicyMapper.xml
  src/main/resources/com/gagechaeum/backend/policy/mapper/RegionMapper.xml
Labels: ✨New Feature

#96 [Feature] #94 : 서류별 상품 목록 조회 API 구현
  src/main/java/com/gagechaeum/backend/document/controller/DocumentProductController.java
  src/main/java/com/gagechaeum/backend/document/dto/response/ItemsByDocumentResponseDto.java
  src/main/java/com/gagechaeum/backend/document/mapper/DocumentMapper.java
  src/main/java/com/gagechaeum/backend/document/service/DocumentProductService.java
  src/main/java/com/gagechaeum/backend/document/service/DocumentProductServiceImpl.java
  src/main/resources/com/gagechaeum/backend/document/mapper/DocumentMapper.xml
Labels: ✨New Feature

#102 [Refactor] #101 : 리포트 API 요청 시 인증된 사용자 정보 사용하도록 수정
  src/main/java/com/gagechaeum/backend/bookmark/dto/response/BookmarkResponseDTO.java
  src/main/java/com/gagechaeum/backend/report/controller/ReportController.java
  src/main/java/com/gagechaeum/backend/report/dto/ReportAllItemResult.java
  src/main/java/com/gagechaeum/backend/report/mapper/ReportMapper.java
  src/main/resources/com/gagechaeum/backend/bookmark/mapper/BookmarkMapper.xml
  src/main/resources/com/gagechaeum/backend/report/mapper/ReportMapper.xml
Labels: 🐞Bug Fix, 🛠Refactor

#104 [Fix] 정책 지역/업종코드 매핑, 닉네임 검증 오류 수정 및 테스트 완료
  init.sql
  src/main/java/com/gagechaeum/backend/policy/dto/external/Gov24ApiServiceDto.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicyMatchingServiceImpl.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicySyncServiceImpl.java
  src/main/java/com/gagechaeum/backend/user/controller/UserController.java
  src/main/java/com/gagechaeum/backend/user/service/UserService.java
  src/main/java/com/gagechaeum/backend/user/service/UserServiceImpl.java
Labels: 🐞Bug Fix

#103 [Feature] : 채팅 첨부파일 업로드/히스토리 조회 처리
  dummy.sql
  init.sql
  src/main/java/com/gagechaeum/backend/chat/controller/ChatController.java
  src/main/java/com/gagechaeum/backend/chat/controller/ChatStompController.java
  src/main/java/com/gagechaeum/backend/chat/dto/ChatAttachmentDto.java
  src/main/java/com/gagechaeum/backend/chat/dto/ChatHistoryMessageDto.java
  src/main/java/com/gagechaeum/backend/chat/dto/ChatMessageDto.java
  src/main/java/com/gagechaeum/backend/chat/dto/SendMessageRequestDto.java
  src/main/java/com/gagechaeum/backend/chat/dto/UploadAttachmentRequestDto.java
  src/main/java/com/gagechaeum/backend/chat/dto/UploadAttachmentResponseDto.java
  src/main/java/com/gagechaeum/backend/chat/dto/UploadedAttachmentDto.java
  src/main/java/com/gagechaeum/backend/chat/mapper/ChatMapper.java
  src/main/java/com/gagechaeum/backend/chat/service/ChatService.java
  src/main/java/com/gagechaeum/backend/chat/service/ChatServiceImpl.java
  src/main/java/com/gagechaeum/backend/common/util/S3ClientUtil.java
  src/main/java/com/gagechaeum/backend/document/service/UserDocumentServiceImpl.java
  src/main/resources/com/gagechaeum/backend/chat/mapper/ChatMapper.xml
Labels: ✨New Feature

#108 [Feature] : 정책 스케줄링
  src/main/java/com/gagechaeum/backend/policy/service/PolicySyncServiceImpl.java
Labels: ✨New Feature

#109 [Fix] #107 : 정책, 대출 즐겨찾기 조회 api 컬럼 오류 수정
  src/main/java/com/gagechaeum/backend/document/dto/response/ItemsByDocumentResponseDto.java
  src/main/resources/com/gagechaeum/backend/bookmark/mapper/BookmarkMapper.xml
Labels: 🐞Bug Fix

#114 feat: 채팅방 생성
  src/main/java/com/gagechaeum/backend/chat/mapper/ChatMapper.java
  src/main/java/com/gagechaeum/backend/chat/service/ChatService.java
  src/main/java/com/gagechaeum/backend/chat/service/ChatServiceImpl.java
  src/main/java/com/gagechaeum/backend/policy/service/PolicySyncServiceImpl.java
  src/main/resources/com/gagechaeum/backend/chat/mapper/ChatMapper.xml
Labels: ✨New Feature

#115 [Fix] : 즐겨찾기 더미데이터 추가
  dummy.sql
Labels: 🐞Bug Fix

#116 [Fix] #111 : 정책 날짜 update 추가
  dummy.sql
Labels: 🐞Bug Fix
